Update pipeline

diff --git a/scripts/pipelines/snakemake_quinn_data/Snakefile b/scripts/pipelines/snakemake_quinn_data/Snakefile
--- a/scripts/pipelines/snakemake_quinn_data/Snakefile
+++ b/scripts/pipelines/snakemake_quinn_data/Snakefile
@@ -20,9 +20,7 @@ for mouse in mouse_ids:
         excluded_cps_5k_by_compute_requirements = ["1", "2", "3", "4", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "17", "19", "20", "21", "22", "23", "27", "31"]
         mouse_cps = [cp for cp in mouse_cps if cp not in excluded_cps_5k_by_original_paper and cp not in excluded_cps_5k_by_compute_requirements]
 
-
-        # specific CPs needing more nested sampling particles
-        mouse_cps = ["61", "52", "92", "90", "97", "82", "85", "49", "94", "100", "76", "89", "91", "95", "54", "73", "48", "71", "78", "77", "46", "68", "29"]
+        # mouse_cps = ["45", "52", "82", "90", "97", "89", "73", "92", "100", "77", "76", "94", "95", "85", "91", "78", "36", "46", "48", "49", "29"]
 
     cps_for_mouse[mouse] = mouse_cps
 
@@ -55,9 +53,9 @@ rule all:
         expand("{outdir}/beam_gtr/{mouse}/all_expected_migration_times_no_multiedge_combined.pdf", outdir=outdir, mouse=mouse_ids),
         expand("{outdir}/beam_gtr/{mouse}/combined_rf_distances.pdf", outdir=outdir, mouse=mouse_ids),
         # expand("{outdir}/mach2/{mouse}/all_consensus_classifications.csv", outdir=outdir, mouse=mouse_ids),
-        [expand("{outdir}/beam_gtr_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 21), outdir=outdir) for m in mouse_ids],
-        [expand("{outdir}/beam_random_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 21), outdir=outdir) for m in mouse_ids],
-        # [expand("{outdir}/beam_gtr_noRLdirectSeeding_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 11), outdir=outdir) for m in mouse_ids],
+        # [expand("{outdir}/beam_gtr_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 31), outdir=outdir) for m in mouse_ids],
+        # [expand("{outdir}/beam_random_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 31), outdir=outdir) for m in mouse_ids],
+        [expand("{outdir}/beam_gtr_noRLdirectSeeding_ns/{mouse}/{cp}/terminal_{num}.log", mouse=m, cp=cps_for_mouse[m], num=range(1, 21), outdir=outdir) for m in mouse_ids],
 
 
 rule plotCountsPerCP:
@@ -1116,8 +1114,6 @@ rule runBeamGtrNoRLDirectSeeding:
         lamlTree = "{outdir}/laml/{mouse}/{cp}/laml_trees.nwk"
     output:
         terminalLog = "{outdir}/beam_gtr_noRLdirectSeeding_ns/{mouse}/{cp}/terminal_{num}.log",
-        beamLog = "{outdir}/beam_gtr_noRLdirectSeeding_ns/{mouse}/{cp}/chain_{num}.log",
-        beamResult = "{outdir}/beam_gtr_noRLdirectSeeding_ns/{mouse}/{cp}/chain_{num}.trees"
     params:
         xml = config['gtrXmlNoRLDirectSeeding'],
         inFileDir = "{outdir}/beam/{mouse}/{cp}",
@@ -1150,72 +1146,65 @@ rule runBeamGtrNoRLDirectSeeding:
         numTissueRates=$(( (((numTissues * numTissues) - numTissues) / 2) - 1 ))
 
         # check if RL is in the tissues and that the tissues do not only have the primary and RL which are both requirements of fitting the model
-        if echo "$unique_tissues" | grep -qw "RL"; then
-            if [ "$numTissues" -le 2 ]; then
-                echo "Only primary tissue and RL are present, not enough tissues to fit the model. Exiting."
-                touch {output.terminalLog}
-                exit 0
-            fi
+        if ! echo "$unique_tissues" | grep -qw "RL" || [ "$numTissues" -le 2 ]; then
+            echo "Either RL tissue is not found or only primary tissue and RL are present, not enough tissues to fit the model. Exiting."
+            touch {output}
         else
-            echo "RL tissue not found in the tissues. Exiting."
-            touch {output.terminalLog}
-            exit 0
+            tissueCodeMap=""
+            trailingCodeMap="? = "
+            i=0
+            for tissue in $sorted_unique_tissues; do
+                tissueCodeMap+="$tissue=$i,"
+                trailingCodeMap+="$i "
+                i=$((i+1))
+            done
+            tissueCodeMap+="${{trailingCodeMap}}"
+
+            # for some reason this cannot be taken in at the command line, likely because the = signs are problematic and not taken as a single string
+            sed -i "s/\$(tissueCodeMap)/$tissueCodeMap/g" {params.fileDir}/{wildcards.num}.xml
+
+            # initial edit rates are often too long to be taken in at a java command line argument for this data, so replace it here
+            sed -i "s/\$(initialEditRates)/$initialEditRates/g" {params.fileDir}/{wildcards.num}.xml
+
+            # use LAML starting tree
+            # remove node names from newick and the origin node
+            newick=$(cat {input.lamlTree} | sed 's/node[0-9]*:/:/g' | sed 's/^.//' | sed 's/..$//')
+
+            # starting newick can often be too long to be taken in at a java command line argument for this data, so replace it here
+            # but even bash commands have length limits, so split the newick string into manageable chunks and replace them one by one
+            chunk_size=1000
+            newick_length=${{#newick}}
+            for ((i=0; i<newick_length; i+=chunk_size)); do
+                chunk=${{newick:i:chunk_size}}
+                sed -i "s/\$(newick)/$chunk\$(newick)/" {params.fileDir}/{wildcards.num}.xml
+            done
+            # Remove the remaining placeholder
+            sed -i "s/\$(newick)//" {params.fileDir}/{wildcards.num}.xml
+
+            # Replace mcmc specs with nested sampling specs
+            mcmc_specs="<run id=\\"mcmc\\" spec=\\"MCMC\\" chainLength=\\"\\$(mcmclength)\\">"
+            ns_specs="<run id=\\"mcmc\\" spec=\\"beast.gss.NS\\" chainLength=\\"100000000\\" particleCount=\\"1\\" subChainLength=\\"10000\\" epsilon=\\"1e-10\\">"
+            sed -i "s/$mcmc_specs/$ns_specs/g" {params.fileDir}/{wildcards.num}.xml
+
+            specifiedIndex=$(echo $sorted_unique_tissues | tr ' ' '\n' | grep -n "^RL$" | cut -d':' -f1)
+            specifiedIndex=$((specifiedIndex - 1))  # convert 1-based index to 0-based for model code compatibility
+
+            echo "RL tissue found at index $specifiedIndex, so index $specifiedIndex will have a rate fixed to 0."
+
+            java -Xmx10g -jar {params.beamJar} \
+            -threads {params.threads} \
+            -overwrite \
+            -working \
+            -D inName={wildcards.mouse}_{wildcards.cp} \
+            -D fileDir={params.inFileDir} \
+            -D generations={params.experimentTime} \
+            -D numEditRates=\"$numEditRates\" \
+            -D numEditRatesPlusTwo=\"$numEditRatesPlusTwo\" \
+            -D numTissueRates=\"$numTissueRates\" \
+            -D numTissues=\"$numTissues\" \
+            -D tissueRootFreqs=\"$tissueRootFreqs\" \
+            -D specifiedIndex=\"$specifiedIndex\" \
+            -D outname=chain_{wildcards.num} \
+            {params.fileDir}/{wildcards.num}.xml > {output.terminalLog}
         fi
-
-        tissueCodeMap=""
-        trailingCodeMap="? = "
-        i=0
-        for tissue in $sorted_unique_tissues; do
-            tissueCodeMap+="$tissue=$i,"
-            trailingCodeMap+="$i "
-            i=$((i+1))
-        done
-        tissueCodeMap+="${{trailingCodeMap}}"
-
-        # for some reason this cannot be taken in at the command line, likely because the = signs are problematic and not taken as a single string
-        sed -i "s/\$(tissueCodeMap)/$tissueCodeMap/g" {params.fileDir}/{wildcards.num}.xml
-
-        # initial edit rates are often too long to be taken in at a java command line argument for this data, so replace it here
-        sed -i "s/\$(initialEditRates)/$initialEditRates/g" {params.fileDir}/{wildcards.num}.xml
-
-        # use LAML starting tree
-        # remove node names from newick and the origin node
-        newick=$(cat {input.lamlTree} | sed 's/node[0-9]*:/:/g' | sed 's/^.//' | sed 's/..$//')
-
-        # starting newick can often be too long to be taken in at a java command line argument for this data, so replace it here
-        # but even bash commands have length limits, so split the newick string into manageable chunks and replace them one by one
-        chunk_size=1000
-        newick_length=${{#newick}}
-        for ((i=0; i<newick_length; i+=chunk_size)); do
-            chunk=${{newick:i:chunk_size}}
-            sed -i "s/\$(newick)/$chunk\$(newick)/" {params.fileDir}/{wildcards.num}.xml
-        done
-        # Remove the remaining placeholder
-        sed -i "s/\$(newick)//" {params.fileDir}/{wildcards.num}.xml
-
-        # Replace mcmc specs with nested sampling specs
-        mcmc_specs="<run id=\\"mcmc\\" spec=\\"MCMC\\" chainLength=\\"\\$(mcmclength)\\">"
-        ns_specs="<run id=\\"mcmc\\" spec=\\"beast.gss.NS\\" chainLength=\\"100000000\\" particleCount=\\"1\\" subChainLength=\\"10000\\" epsilon=\\"1e-10\\">"
-        sed -i "s/$mcmc_specs/$ns_specs/g" {params.fileDir}/{wildcards.num}.xml
-
-        specifiedIndex=$(echo $sorted_unique_tissues | tr ' ' '\n' | grep -n "^RL$" | cut -d':' -f1)
-        specifiedIndex=$((specifiedIndex - 1))  # convert 1-based index to 0-based for model code compatibility
-
-        echo "RL tissue found at index $specifiedIndex, so index $specifiedIndex will have a rate fixed to 0."
-
-        java -Xmx10g -jar {params.beamJar} \
-        -threads {params.threads} \
-        -overwrite \
-        -working \
-        -D inName={wildcards.mouse}_{wildcards.cp} \
-        -D fileDir={params.inFileDir} \
-        -D generations={params.experimentTime} \
-        -D numEditRates=\"$numEditRates\" \
-        -D numEditRatesPlusTwo=\"$numEditRatesPlusTwo\" \
-        -D numTissueRates=\"$numTissueRates\" \
-        -D numTissues=\"$numTissues\" \
-        -D tissueRootFreqs=\"$tissueRootFreqs\" \
-        -D specifiedIndex=\"$specifiedIndex\" \
-        -D outname=chain_{wildcards.num} \
-        {params.fileDir}/{wildcards.num}.xml > {output.terminalLog}
         """
